name: Sync Docs to gh-pages

on:
  push:
    branches: [ "main" ]  # Cambia a "master" si esa es tu rama fuente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "Brayan-CVR"
          git config user.email "brayanv395@gmial.com"

      - name: Preparar archivos
        run: |
          # Crear carpeta temporal CON los archivos a copiar
          mkdir -p gh-pages-content
          cp -R docs/build/html/* gh-pages-content/

      - name: Actualizar gh-pages
        run: |
          # Cambiar a la rama gh-pages (se crea si no existe)
          git checkout --orphan gh-pages || git checkout gh-pages
          
          # Conservar solo estos archivos
          for file in .gitignore .nojekyll; do
            if [ -f "$file" ]; then
              mv "$file" ../ 
            fi
          done
          
          # Limpiar TODO excepto .git
          rm -rf * .[^.]* || true
          
          # Restaurar archivos protegidos
          for file in .gitignore .nojekyll; do
            if [ -f "../$file" ]; then
              mv "../$file" .
            fi
          done
          
          # Copiar contenido nuevo
          cp -R gh-pages-content/* .
          rm -rf gh-pages-content
          
          # Hacer commit (solo si hay cambios)
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Actualización automática: $(date +'%F %T')"
            git push origin gh-pages
          fi