name: Sync Folder to Target Branch

on:
  push:
    branches: [ "main" ]

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "Brayan-CVR"
          git config user.email "brayanv395@gmial.com"

      - name: Copy files
        run: |
          mkdir -p temp_copy
          cp -R docs/build/html/* temp_copy/

      - name: Update target branch
        run: |
          git checkout gh-pages 
          mv .nojekyll ..
          # Limpieza
          find . -mindepth 1 ! -name '.git' -exec rm -rf {} +
          # Restaura y copia
          mv ../.nojekyll .
          cp -R ../temp_copy/* .
          rm -rf ../temp_copy
          # Commit
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-sync from main $(date +'%Y-%m-%d')"
            git push origin gh-pages
          fi