name: Sync Docs to gh-pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build docs (ejemplo para Sphinx)
        run: |
          pip install -r docs/requirements.txt
          cd docs && make html

      - name: Prepare gh-pages
        run: |
          # Configuración esencial de Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Obtener la rama gh-pages
          git fetch origin gh-pages:gh-pages
          
          # Crear directorio de trabajo
          mkdir -p publish
          cp -R docs/build/html/* publish/

      - name: Deploy to gh-pages
        run: |
          git checkout gh-pages
          
          # Limpieza selectiva
          find . -maxdepth 1 ! -name '.git' ! -name '.nojekyll' -exec rm -rf {} +
          
          # Copiar archivos construidos
          cp -R publish/* .
          rm -rf publish
          
          # Commit y push
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Docs update $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin gh-pages
          fi